### ISSUE TITLE
More Modded Support

### ISSUE THREAD

**Issue by WenXin20** [bl4ckscor3/CeilingTorch#12]
- [Secret Rooms](https://www.curseforge.com/minecraft/mc-mods/secretroomsmod)  & [Inspirations](https://www.curseforge.com/minecraft/mc-mods/inspirations)  both add a Torch Lever
- [Torcherino](https://www.curseforge.com/minecraft/mc-mods/torcherino)  torches speed up the tick rate
- [The Gaia Dimension](https://www.curseforge.com/minecraft/mc-mods/gaia-dimension) , [Tofucraft](https://www.curseforge.com/minecraft/mc-mods/tofucraftreload) , & [Nethercraft](https://www.curseforge.com/minecraft/mc-mods/nethercraft-classic)  adds regular torches
- [Wild Nature](https://www.curseforge.com/minecraft/mc-mods/wildnature) adds torches and a Redstone Torch.
- [Essential Features](https://www.curseforge.com/minecraft/mc-mods/essential-features) adds colored Redstone torches.

**Comment by EternalOne11** [comment]
Bamboo blocks adds a new torch varient as well.
