### ISSUE TITLE
Chance Globe mod in ceilingtorch-1.12.2-v1.2.jar

### ISSUE THREAD

**Issue by Reisanji** [bl4ckscor3/CeilingTorch#2]
Just grabbed it again from curse.
![ceiling_chance](https://user-images.githubusercontent.com/53265963/61799809-62556d00-adf1-11e9-8d66-ed53c8f1c1d7.png)

I deleted it from the original jar last night and haven't run into any problems so I figure it's not needed.

**Comment by brisingraerowing** [comment]
This explains why I got that config file.

**Comment by Reisanji** [comment]
That config's what made me dive deeper.

**Comment by bl4ckscor3** [comment]
Uh, sorry for just seeing this now. I'll upload a fixed jar file. I should better pay attention when copying code from my other mods :)
