### ISSUE TITLE
[1.16.1-Request] Add Support for DwarfCoal Mod.

### ISSUE THREAD

**Issue by Gbergz** [bl4ckscor3/CeilingTorch#23]
Title^

Is it possible to add support for the mod DwarfCoal's Stone Torch, Dwarf Stone Torch & Regular Dwarf Torch. (1.16.1)
**Mod Page:** https://www.curseforge.com/minecraft/mc-mods/dwarf-coal

**These torches:**
![image](https://user-images.githubusercontent.com/26634554/89712604-44be5b80-d992-11ea-958e-c0b0246a6f25.png)

**Item IDs**
**dwarfcoal:stone_torch**, **dwarfcoal:stone_dwarf_torch** & **dwarfcoal:dwarf_torch**

Thanks,
**-** Gbergz

**Comment by bl4ckscor3** [comment]
https://www.curseforge.com/minecraft/mc-mods/ceiling-torch/files/3027669
