### ISSUE TITLE
[1.14.3] Loottable Issue on SMP

### ISSUE THREAD

**Issue by Morpheus1101** [bl4ckscor3/CeilingTorch#3]
When loading a SMP server although the mod loads aok, it errors on console about a lot of loottable refrences as per snippet of log Line 106+ @  https://pastebin.com/xfaPBYaT

If your working on a 1.14.4 build .. then i'll simply ignore this an wait for the 1.14.4 version

**Comment by bl4ckscor3** [comment]
Sorry for just seeing this now. Could you please reupload the paste? It has expired.

**Comment by Morpheus1101** [comment]
Apologies for delay, got stuyck back in 1.12.2 .. here is the pastebin with a large snippet of console issues related to this report. 
https://pastebin.com/Uipm8Lmn

**Comment by Morpheus1101** [comment]
ok, so basically same as #5 so closing this one
