### ISSUE TITLE
[1.16.5] Druidcraft support broken.

### ISSUE THREAD

**Issue by Gbergz** [bl4ckscor3/CeilingTorch#31]
Title ^

Can't seem to place Druidcraft torches in the ceiling anymore.

**MC:** 1.16.5
**Forge:** 336.0.13
**Celing torch:** 1.9.1

**Comment by bl4ckscor3** [comment]
That's because Druidcraft support has not yet been added for 1.16 (see list on CurseForge). I will get to this when I have the time.
