### ISSUE TITLE
Crash with new inspirations version

### ISSUE THREAD

**Issue by EternalOne11** [bl4ckscor3/CeilingTorch#32]
It crashes on the new inspirations version.

https://www.curseforge.com/minecraft/mc-mods/inspirations/files/3308942

**Comment by Warbringer12** [comment]
ive come across this too just starting today

**Comment by MoonMoonShark** [comment]
funny, i just came here to list this, and found i'm not the only one. :) so, it seems this would be a confirmed bug now.

**Comment by bl4ckscor3** [comment]
You don't need to say "this happens to me as well", it adds no valuable information to the discussion. I added the "bug" label a week ago already. This will be fixed when I have the time.
