### ISSUE TITLE
Crashing with Gaia Dimension

### ISSUE THREAD

**Issue by judicius** [bl4ckscor3/CeilingTorch#33]
Minecraft: 1.16.5 
Forge: [e.g. 36.1.23
Gaia Dimension: 1.3.3
Ceiling Torch 1.10

Crash Report
https://gist.github.com/judicius/2c992b753d668f5d2212db72e76be154

Highlighted issue from Gaia dev
https://github.com/bl4ckscor3/CeilingTorch/blob/5370f72b6b20218efcc5e05934a89ffbda5784d9/src/main/java/bl4ckscor3/mod/ceilingtorch/compat/gaiadimension/GaiaDimensionCompat.java#L30

**Comment by Bidgam** [comment]
Confirmed, experiencing this as well.
