### ISSUE TITLE
Unable to Start Up Modded Minecraft with the Ceiling Torch Mod

### ISSUE THREAD

**Issue by MarioMario24680** [bl4ckscor3/CeilingTorch#34]
Hello, my Minecraft version is 1.16.5 and my Forge version is 36.1.24. The file version of the Ceiling Torch mod I have is v1.10. When I try to start up the Minecraft client, it runs for several seconds before suddenly bringing up an error screen and saying "Ceiling Torch (ceilingtorch) encountered an error during the load_registries event phase." Here is the crash report file: [crash-2021-05-28_11.23.14-fml.txt](https://github.com/bl4ckscor3/CeilingTorch/files/6562129/crash-2021-05-28_11.23.14-fml.txt)

On its own, the Ceiling Torch mod doesn't create this error while Forge is loading, but when I include it in a custom modpack where I've tested out every other mod (and those other mods were all stable and functional), it starts to generate this error whenever I start up Minecraft. This above crash report mentions assets for TofuCraft (version 0.3.7.5 for Minecraft 1.16.5), but even when I take TofuCraft out of the modpack, the Ceiling Torch mod error still appears. I was planning on using it for a Forge 36.1.24 (Minecraft 1.16.5) server, but this currently appears to be just a client-side issue, rather than a server-side crash.  Here is a list of all the mods that I want to include in my modpack: [Good Mods.txt](https://github.com/bl4ckscor3/CeilingTorch/files/6562150/Good.Mods.txt)

If there's any more information you need to know, please tell me and I'll try to help you as best as I can. Please fix this problem.

**Comment by bl4ckscor3** [comment]
This is caused by an update from TofuCraftReload, which broke compatibility with Ceiling Torch. I will have to update Ceiling Torch to fix this.
