### ISSUE TITLE
Ceiling Torch (version 1.11) Client-Side and Server-Side Start-Up Crash for Minecraft 1.16.5 (Forge 36.1.24)

### ISSUE THREAD

**Issue by MarioMario24680** [bl4ckscor3/CeilingTorch#35]
Hello, I'm back again. I noticed a new problem with the latest version of Ceiling Torch (v1.11). From what I can tell, it's being caused by an interaction with the Inspirations mod:

![image](https://user-images.githubusercontent.com/76149435/120721805-2fbc3700-c494-11eb-86d7-381e063cbf41.png)

Client-Side Crash Report: 
[crash-2021-06-03_17.45.35-fml.txt](https://github.com/bl4ckscor3/CeilingTorch/files/6594728/crash-2021-06-03_17.45.35-fml.txt)

Server-Side Crash Report: 
[crash-2021-06-03_17.43.34-fml.txt](https://github.com/bl4ckscor3/CeilingTorch/files/6594731/crash-2021-06-03_17.43.34-fml.txt)

**Comment by bl4ckscor3** [comment]
Update Inspirations.
