### ISSUE TITLE
Additional Torches

### ISSUE THREAD

**Issue by WenXin20** [bl4ckscor3/CeilingTorch#37]
Here are several mods that also adds torches that could potential have support for:
- [Framed Blocks](https://www.curseforge.com/minecraft/mc-mods/framedblocks) - Framed Torch & Soul Torch (Can be right-clicked to use texture of any block)
- [Chaos Awakens'](https://www.curseforge.com/minecraft/mc-mods/chaos-awakens) Crystal, Sunstone, & Extreme Torches
- [Valhelsia Structures'](https://www.curseforge.com/minecraft/mc-mods/valhelsia-structures) Doused Torches
- [Infernal Expansion's](https://www.curseforge.com/minecraft/mc-mods/infernal-expansion) Glowlight Torch
- [Malum's](https://www.curseforge.com/minecraft/mc-mods/malum) colored Ether Torches
- [Undergarden's](https://www.curseforge.com/minecraft/mc-mods/the-undergarden) Shard Torch
- [Endergetic's](https://www.curseforge.com/minecraft/mc-mods/endergetic) Ender Torch
- [Atum's](https://www.curseforge.com/minecraft/mc-mods/atum) 20 Torches

**Comment by bl4ckscor3** [comment]
I won't be adding compatibility for Framed Blocks. I will slowly be looking at the others over the next couple days and then release an update.

**Comment by WenXin20** [comment]
Alright, fair enough. Thanks for looking into them.

**Comment by bl4ckscor3** [comment]
I looked into Valhelsia Structures as well, but their "torch dousing system" is not feasibly adaptable for other mods wanting to use it to douse their torches, so I will hold off on adding support for this mod for now.
