### ISSUE TITLE
Crash w/ Infernal Expansion

### ISSUE THREAD

**Issue by WenXin20** [bl4ckscor3/CeilingTorch#39]
`Minecraft v1.16.5`
`Forge v36.1.32`
`Ceiling Torch v1.13`
`Infernal Expansion v2.0.0-beta.5`

I got this crash during load with Infernal Expansion when using their beta version obtained from [Modrinth](https://modrinth.com/mod/infernalexpansion/version/Wxjxe9kM), since it is not yet available on Curseforge. Though it's understandable if you'd rather wait till it is released on curseforge.
[Crash Report](https://gist.github.com/WenXin20/9b81e64b0af4726efe8a61fb160683d6)

**Comment by bl4ckscor3** [comment]
I'll wait until the full release which will be available on CurseForge according to their Twitter account. If they change more during the beta, I'll have to update Ceiling Torch yet again.

**Comment by WenXin20** [comment]
The latest update has been released on curseforge: https://www.curseforge.com/minecraft/mc-mods/infernal-expansion/files/3389285

**Comment by bl4ckscor3** [comment]
It's still marked as a beta, but I'll just hope I don't have to update Ceiling Torch again due to changes in the same code area.

**Comment by WenXin20** [comment]
Thanks! Hopefully not.
