### ISSUE TITLE
[1.14.4] Forge Dependancy Issue loading Client

### ISSUE THREAD

**Issue by Morpheus1101** [bl4ckscor3/CeilingTorch#4]
Im running Forge 28.0.9 however the mod dosent like it and is requiring 28.0.45 or higher, which obviously im using.

**Comment by bl4ckscor3** [comment]
Huh? You're using Forge 28.0.9, which is old (released on the 20th of July). The mod requires 28.0.45 (released on the 5th of August) or newer. So use Forge 28.0.45 or newer? x.x.9 is lower (older) than x.x.45. The mod won't work on anything below 28.0.45, as needed functionality was added in 28.0.45.
EDIT: Closing this. Feel free to reopen with further information if it doesn't work once you tried Forge 28.0.45+

**Comment by Morpheus1101** [comment]
Arg, apologies, stupid Curse client...i though 28.0.9 was 28.0.90 .. i will remedy this which will solve all my issues
