### ISSUE TITLE
Ceiling torches have collision

### ISSUE THREAD

**Issue by WenXin20** [bl4ckscor3/CeilingTorch#42]
`Minecraft v1.16.5`
`Forge v36.1.32`
`Ceiling Torch v1.13.1`

Upon placing a Ceiling Torch, I found out that I could not walk through it.

**Comment by bl4ckscor3** [comment]
Seems to work for me. 

https://user-images.githubusercontent.com/5149876/126003578-57622b06-9e7f-4a03-8055-2ed9c43b6fa8.mp4

**Comment by WenXin20** [comment]
Strange, I'll send a video. Maybe one of the compat torches causes it?

**Comment by bl4ckscor3** [comment]
I doubt it, because collision is a per-block setting. But I'll try with all compats turned on.

EDIT: No, that's not it. Collision is still working as intended.

**Comment by WenXin20** [comment]
Figured it out, there was a snow layer under the ceiling torch. For some reason, the snow layer becomes a solid block when a ceiling torch is above it. I will test a bit more to see if that happens with only ceiling torches.

(It got pretty laggy while recording)

https://user-images.githubusercontent.com/12000593/126025126-389b01ac-fca0-4532-bdc1-2473f5f61ac2.mp4

With the Orc Torch from Lord of the Rings, I was able to stand above the snow layer as a full block collision.

![2021-07-16_23 04 02](https://user-images.githubusercontent.com/12000593/126025189-f85e6273-0a03-47c4-997c-5d8b3e4cb1de.png)

**Comment by bl4ckscor3** [comment]
I still cannot reproduce the issue on my end, it could be that one of the other mods you have installed is changing how snow's collision works, and contains a bug in that logic.

https://user-images.githubusercontent.com/5149876/126032275-012c1427-66eb-43f2-a2f8-3a90c9b90290.mp4

**Comment by WenXin20** [comment]
Ok, tested it a bit more, and the snow layer collision becomes solid with any block placed above it, including wall torches. I suspect that snow real magic is the cause of it. Looks like it was just pure luck that I found this bug. :D.
