### ISSUE TITLE
Crash w/ Malum

### ISSUE THREAD

**Issue by WenXin20** [bl4ckscor3/CeilingTorch#43]
`Minecraft v1.16.5`
`Forge v36.1.32`
`Ceiling Torch v1.13.1`
[`Malum v0.3.0`](https://www.curseforge.com/minecraft/mc-mods/malum)

While trying to test if the mod compat ceiling torches have the collision bug, I got a crash with Malum torches when placing it on the ceiling. On a server, I crashed client-side.
[Crash Report](https://gist.github.com/WenXin20/eeaf0253b4739651af008521d463b364)

**Comment by bl4ckscor3** [comment]
I can't reproduce this crash with only Ceiling Torch and Malum, the ceiling torch particles render fine. Maybe some other mod is messing with the rendering of Malum? Do Malum's torches work when placed normally?

**Comment by WenXin20** [comment]
Hmm, not sure. I'll give it a try. I have Sodium Reforged installed, so maybe that causes it.

**Comment by WenXin20** [comment]
Yep, crashes as a normal torch too. Must be on Malum's side
