### ISSUE TITLE
Glowlight Torch Missing Model

### ISSUE THREAD

**Issue by WenXin20** [bl4ckscor3/CeilingTorch#44]
`Minecraft v1.16.5`
`Forge v36.1.32`
`Ceiling Torch v1.13.1`
`Infernal Expansion v2.0.0-beta 6`

The glowlight torch is missing its model and texture.

![2021-07-16_23 06 05](https://user-images.githubusercontent.com/12000593/126025251-3760c364-657e-434f-8768-751a83f61001.png)

**Comment by bl4ckscor3** [comment]
Sorry, oversight on my part.
