### ISSUE TITLE
Compability issue with Infernal Expansion?

### ISSUE THREAD

**Issue by lebagvondouche** [bl4ckscor3/CeilingTorch#45]
Hi, cant get these mods to load together:

https://gist.github.com/haeihaiehaei/87de932144c155eb10562fded62ac0b0

**Comment by bl4ckscor3** [comment]
Update Infernal Expansion to 2.0.0-7 or downgrade Ceiling Torch to v1.13.

**Comment by Gbergz** [comment]
Seems to be happening again?
https://gist.github.com/Gbergz/b975d078f9e2891b65d457de477799c7

Using:
**Forge:** 36.2.2
**Infernal Expansion:** 2.1.1
**Ceiling Torch:** 1.13.2

**Comment by bl4ckscor3** [comment]
Thanks for reporting, I fixed it in v1.13.3. However, please open a new issue next time so it's easier to track them.

**Comment by Gbergz** [comment]
Will do, thanks for the fix! :)
