### ISSUE TITLE
[1.16.5] The Endergetic Expansion x Bamboo Blocks Torch

### ISSUE THREAD

**Issue by TheSnowyChickens** [bl4ckscor3/CeilingTorch#49]
Hello,
bamboo blocks torch "bamboo_blocks:ender_bamboo_torch" can't be placed on the ceiling.
(I think this torch is an addon from "The Endergetic Expansion" mod, could you maybe take a look in this torch ?

![grafik](https://user-images.githubusercontent.com/29357962/129463068-ae91c75d-1b5b-4a03-85b5-77c00a9cd2ab.png)

MC: v1.16.5
Forge: v36.2.2
BBB: v3.0.0
CT: v1.13.4

I saw Endergetic support in your Curse support list and the normal torch from endergetic work fine, so I was wondering about this specific torch.

**Comment by bl4ckscor3** [comment]
I was unaware that this torch exists. I'll update the mod 👍

**Comment by TheSnowyChickens** [comment]
:D
"a new challenger is approaching"

Ty for the update <3
