### ISSUE TITLE
Framed Blocks support?

### ISSUE THREAD

**Issue by Syndaryl** [bl4ckscor3/CeilingTorch#54]
FramedBlocks by XFactHD
https://www.curseforge.com/minecraft/mc-mods/framedblocks
https://github.com/XFactHD/FramedBlocks

FramedBlocks has a "framed torch", and it also has "camouflaged" framed torches, where the texture of another block is applied to the framed torch.

You could speak to XFactHD about interacting with his mod, he's pretty responsive.

**Comment by bl4ckscor3** [comment]
I've previously rejected adding support for this mod due to technical reasons, but I will reconsider.
