### ISSUE TITLE
Crash w/ Malum

### ISSUE THREAD

**Issue by WenXin20** [bl4ckscor3/CeilingTorch#57]
`Minecraft v1.18.1`
`Forge v36.1.2`
[`Malum v1.3.2`](https://www.curseforge.com/minecraft/mc-mods/malum/files/3760494)
`Ceiling Torch v1.15`

Malum had an update, which now causes a crash with Ceiling Torch.
I also just saw that this was fixed for 1.18.2, but not for 1.18.1 if it's still being supported.
[Crash Report](https://gist.github.com/WenXin20/cb64d794bb403eebb08b8e89b01a4d7b)

**Comment by bl4ckscor3** [comment]
Already fixed in v1.16 (no issue present) and again in v1.16.1 (#56). I no longer support 1.18.1 in favor of 1.18.2.

**Comment by WenXin20** [comment]
Alright, good to know, thanks.
