### ISSUE TITLE
Support for these 2 mods

### ISSUE THREAD

**Issue by TheeMrCheeky** [bl4ckscor3/CeilingTorch#64]
https://www.curseforge.com/minecraft/mc-mods/alexs-mobs

Alex mobs has a torch called glowlight torch (idk if there is any others)

https://www.curseforge.com/minecraft/mc-mods/framedblocks

Framed blocks adds a few different types of torches

**Comment by bl4ckscor3** [comment]
I will definitely look into Alex's Mobs, but regarding FramedBlocks, see #54.

**Comment by bl4ckscor3** [comment]
Are you sure Alex's Mobs is the mod that the glowlight torch is from? It doesn't have one in the versions I checked (1.18.6 and 1.20.2 for Minecraft 1.18.2 and 1.19.2 respectively).

**Comment by TheeMrCheeky** [comment]
My apologies I thought it was Alex mobs,  it is  https://www.curseforge.com/minecraft/mc-mods/infernal-expansion

**Comment by TheeMrCheeky** [comment]
which you already have!
so again sorry :D
