### ISSUE TITLE
[Suggestion] Add Support for "Fiery Torch" from the mod Druidcraft.

### ISSUE THREAD

**Issue by Gbergz** [bl4ckscor3/CeilingTorch#7]
As the title suggests: Add Support for "Fiery Torch" from the mod Druidcraft.

Would be awesome! :)

Druidcraft CurseForge page: [https://www.curseforge.com/minecraft/mc-mods/druidcraft](https://www.curseforge.com/minecraft/mc-mods/druidcraft)

- Gbergz

**Comment by bl4ckscor3** [comment]
https://www.curseforge.com/minecraft/mc-mods/ceiling-torch/files/2857207

**Comment by Gbergz** [comment]
Awesome, thank you!
