### ISSUE TITLE
[1.19.2] Occultism compat broke with their latest updates.

### ISSUE THREAD

**Issue by Gbergz** [bl4ckscor3/CeilingTorch#71]
Title ^

### Versions:
MC: 1.19.2
Forge: 43.2.11
Ceiling Torch: 1.24
Occultism: 1.84.1

### Crash Report
Link: https://gist.githubusercontent.com/Gbergz/ba1f76c7e2abc4ed6f022c24f3512569/raw/0103ba99fea7da54cc103ad62a32ef35d27c0315/gistfile1.txt

**Comment by bl4ckscor3** [comment]
The release containing this fix will be the last one for 1.19.2. After that, I will no longer update Ceiling Torch for this version of Minecraft. I will however add a config that allows players to turn off integration with specific mods, meaning they can continue playing if an integration breaks, even if there will not be a fix for it.

**Comment by Gbergz** [comment]
Gotcha!
Thank you for the fix and the disable integration configs :)
