### ISSUE TITLE
CeilingTorch errors on latest neoforge beta

### ISSUE THREAD

**Issue by JoshSagnella** [bl4ckscor3/CeilingTorch#78]
Following error on NeoForge 21.0.86

Details:
	Mod File: /C:/XXX/mods/ceilingtorch-1.21-1.29.jar
	Failure message: fml.modloadingissue.failedtoloadmod
	Mod Version: 1.29
	Mod Issue URL: https://github.com/bl4ckscor3/CeilingTorch/issues
	Exception message: java.lang.NoSuchMethodError: 'void net.neoforged.neoforge.common.ModConfigSpec.setConfig(com.electronwill.nightconfig.core.CommentedConfig)'

**Comment by bl4ckscor3** [comment]
Thank you for reporting! This is already fixed in dev, however I want to go over the mods to see for which I can readd compatibility. I'll try to get it released today.

For the record: Fixed in aa18829
