### ISSUE TITLE
Support for Upgrade Aquatic, Modernity, &/or Torch Master

### ISSUE THREAD

**Issue by WenXin20** [bl4ckscor3/CeilingTorch#8]
Could Ceiling Torch support be added for [Torch Master](https://www.curseforge.com/minecraft/mc-mods/torchmaster), [Upgrade Aquatic](https://www.curseforge.com/minecraft/mc-mods/upgrade-aquatic) , &/or [The Modernity](https://www.curseforge.com/minecraft/mc-mods/the-modernity)  mods in 1.14?

Also, the Jelly Torches from Upgrade Aquatic can be waterlogged.

**Comment by bl4ckscor3** [comment]
https://www.curseforge.com/minecraft/mc-mods/ceiling-torch/files/2858580
