### ISSUE TITLE
[Suggestion] Add Support for "Stone Torch" from the mod Silent Gear.

### ISSUE THREAD

**Issue by Gbergz** [bl4ckscor3/CeilingTorch#9]
As the title suggests: Add Support for "Stone Torch" from the mod [Silent Gear](https://www.curseforge.com/minecraft/mc-mods/silent-gear).

Would be cool! 

Silent Gear CurseForge page: [https://www.curseforge.com/minecraft/mc-mods/silent-gear](https://www.curseforge.com/minecraft/mc-mods/silent-gear)

Appears i can't find it in the Creative Menu or JEI, but here's the ID for it.
<item:silentgear:stone_torch>

- Gbergz

**Comment by bl4ckscor3** [comment]
https://www.curseforge.com/minecraft/mc-mods/ceiling-torch/files/2858580
